includes: ./db/db.config.yaml
    ./events-stack/opensearch.config.yaml
    ./nginx/nginx.config.yaml
    ./suricata/suricata.config.yaml
    ./scirius/scirius.config.yaml
    ./scout/scout.config.yaml
    ./utils/utils.config.yaml

globals:
    restartmode:
        type: string
        usage: Restart mode for all services
        default: unless-stopped
        choices: restart







